apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-lvlm
  namespace: mvp-dev-ripl-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:8416746468fcfa7992d1c9b329a94c3dee9aacf228d84e234a7ad46183ccf225
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
